"""Create initial database schema

Revision ID: b651a6fee18c
Revises:
Create Date: 2026-07-22 23:19:13.286307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b651a6fee18c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name='ck_branches_name_not_blank'),
    sa.PrimaryKeyConstraint('id', name='pk_branches'),
    sa.UniqueConstraint('name', name='uq_branches_name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'common_user'"), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'admin' AND branch_id IS NULL) OR (role = 'common_user' AND branch_id IS NOT NULL)", name='ck_users_branch_assignment'),
    sa.CheckConstraint("role <> 'admin' OR username = 'admin'", name='ck_users_admin_username'),
    sa.CheckConstraint("role IN ('admin', 'common_user')", name='ck_users_role'),
    sa.CheckConstraint("username <> 'admin' OR role = 'admin'", name='ck_users_reserved_admin_username'),
    sa.CheckConstraint('char_length(btrim(username)) > 0', name='ck_users_username_not_blank'),
    sa.CheckConstraint('deleted_at IS NULL OR is_active = FALSE', name='ck_users_soft_delete_state'),
    sa.CheckConstraint('token_version >= 0', name='ck_users_token_version_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_users_branch_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_active', ['is_active'], unique=False)
        batch_op.create_index('ix_users_branch_id', ['branch_id'], unique=False)
        batch_op.create_index('uq_users_single_admin', ['role'], unique=True, postgresql_where=sa.text("role = 'admin'"))

    op.create_table('stocks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('external_product_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(external_product_id)) > 0', name='ck_stocks_external_product_id_not_blank'),
    sa.CheckConstraint('quantity >= 0', name='ck_stocks_quantity_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_stocks_branch_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_stocks'),
    sa.UniqueConstraint('branch_id', 'external_product_id', name='uq_stocks_branch_product')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index('ix_stocks_branch_quantity', ['branch_id', 'quantity'], unique=False)
        batch_op.create_index('ix_stocks_external_product_id', ['external_product_id'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.CheckConstraint("token_type IN ('access', 'refresh')", name='ck_revoked_tokens_type'),
    sa.CheckConstraint('char_length(btrim(jti)) > 0', name='ck_revoked_tokens_jti_not_blank'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_revoked_tokens_user_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='pk_revoked_tokens'),
    sa.UniqueConstraint('jti', name='uq_revoked_tokens_jti')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_revoked_tokens_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_revoked_tokens_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_revoked_tokens_user_id')
        batch_op.drop_index('ix_revoked_tokens_expires_at')

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index('ix_stocks_external_product_id')
        batch_op.drop_index('ix_stocks_branch_quantity')

    op.drop_table('stocks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_single_admin', postgresql_where=sa.text("role = 'admin'"))
        batch_op.drop_index('ix_users_branch_id')
        batch_op.drop_index('ix_users_active')

    op.drop_table('users')
    op.drop_table('branches')
    # ### end Alembic commands ###
